### PR TITLE
Rewrite service-runner in Python

### PR DESCRIPTION
**Pull request by greeebs**
Since the switch to redis, the bash script version of service-runner causes unnecessary load on redis due to having to create a new connection every iteration of the loop. Rewriting it in Python uses a persistent connection to redis.

### CODE REVIEW

**Comment by greeebs** [comment]
Original discussion thread that started this off:
https://community.openenergymonitor.org/t/rpi-3b-getting-hot-redis-high-cpu-usage-emonsd-13jun18-dev-specific/8263

**Comment by glynhudson** [comment]
Hi @greeebs,

Thanks for this, I've just tried to test. First I needed to install the python redis module

 `pip install redis`

Now when I run the python service runner it seems to run then exit without printing anything. Is there anything I'm misssing?

```
$ pi@emonpi:~/emonpi $ ./service-runner
$
```

**Comment by borpin** [comment]
I would suggest taking out all the PID stuff and simply make a systemd control file to run this as a daemon.

Let the builtin OS tools do all that stuff for you.

**Comment by greeebs** [comment]
On the subject of systemd, looking at the existing emonSD-13Jun18 image, any tips on where the service unit files should actually  end up? There doesn't appear to be anything emon related under /etc/systemd/system - it looks like all of the existing ones are sitting under the SysV init folder structure?

**Comment by greeebs** [comment]
Looks like I've had a git fail trying to add additional changes... I'll try and clean that up!

**Comment by glynhudson** [comment]
Great, just tested the systemd update. It works well for me. 

I see you renamed `service-runner` to `service-runner.py`, this is a good idea since if you restored `service-runner` this would mean that older systems could continue to run the older cron bash version. and the new Stretch image I'm working on will use the new systemd version. Users can obviously choose to self upgrade. 

We should probably also add upgrade instructions, something along the lines of

 ```
git pull 
sudo pip install redis
sudo ln -s /home/pi/emonpi/service-runner.service /etc/systemd/system
sudo systemctl daemon-reload
sudo systemctl enable service-runner
sudo systemctl start service-runner
sudo systemctl status service-runner
```
 

Anyone else like to test before I merge @borpi @Paul-Reed

**Comment by glynhudson** [comment]
> Looks like I've had a git fail trying to add additional changes... I'll try and clean that up!

Don't worry, it happens! At least all the changes look like their preset and correct

**Comment by greeebs** [comment]
> We should probably also add upgrade instructions, something along the lines of

I agree. Where would those instructions go?

> Don't worry, it happens! At least all the changes look like their preset and correct

I don't use git enough to be completely confident in what I'm doing... I've somehow merged a heap of commits from a different branch into here but yes the particular files I changed are all there and correct.
Clean-up attempt is continuing :)

**Comment by glynhudson** [comment]
I've added install instructions and restored the old bash service runner to maintain compatibility with older systems. 

I wasn't able to push commits to your PR, in the future it would be a good idea to tick the "allow edits from maintainers" box when opening a PR: https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/

For now I've pushed all our changes up as a new branch on this repo and opened another PR https://github.com/openenergymonitor/emonpi/pull/66

**Comment by glynhudson** [comment]
I will close this PR, please use the new one

**Pull request closed without merging**
