### PR TITLE
Relay dev

### PR DESCRIPTION
**Pull request by Basazababo**
Merging with beaglebone branch

### CODE REVIEW

**Comment by glynhudson** [comment]
Wow, lots of changes here. It's great that you are running on a BB :+1: 

How do you think we can best manage compatibility? A seperate BB emonPi repo or a BB branch of this emonPi repo?

**Comment by Basazababo** [comment]
Actually i did this by mistake but the good thing is that it`s running on bbb,
the man behind this is @jlark,

**Comment by jlark** [comment]
Hello again @glynhudson, we've indeed ported the emon to the BBB and have switched to ansible for deploying some of our own stuff on to it. 

I think @Basazababo pushed this to your repo by mistake but we'd be more than happy to add this to the parent repo.  Does it make sense to keep it in a separate branch on the main repo?

**Comment by glynhudson** [comment]
Maybe it's best to keep your repo where is is currently to avoid user  confusion. Have you documented / blogged about running emoncms on a bb? It would be great to do a post about bb on our blog. I would be happy to credit your project

**Pull request closed without merging**
