### PR TITLE
Add support for Dallas DS2438 temperature readings used in MS-T temperature sensors

### PR DESCRIPTION
**Pull request by alandpearson**
The DS2438 is commonly used in a lot of ibuttonlink.com sensors which
are very popular
https://www.ibuttonlink.com/collections/1-wire-temperature-sensors

These plug straight into the emonpi and are very useful.

The DS2438 also has other capabilites for measuring DC Voltage and
current which are not added in this commit. Maybe someday..

### CODE REVIEW

**Comment by glynhudson** [comment]
Nice work. Does this effect ds18b20 operation in any way? Do you see any issues having this enabled for all users?

**Comment by alandpearson** [comment]
Hi Glyn,
The DS18B20 is unaffected. I run both devices on the same bus. This just adds support for DS2438 if it's found on the bus and processes it correctly.
I'd love if this was for all users, as it would save me running 'special' firmware on the emonpi & emonTx, so if you could merge it, that would be great.

Unrelated to this...  I found a problem when I compile the firmware using all the right libraries as dictated by platform IO ... the call to rf12_initialise kills reception when it is made a 2nd time (Ie the lines
 if ((now - last_rf_rest) > RF_RESET_PERIOD) {
      rf12_initialize(nodeID, RF_freq, networkGroup);                             // Periodically reset RFM69CW to keep it alive :-(
    }

I had to comment those out, and all works really well. I tried with different versions of jee lib and even the openenergymon jee lib fork.     Running the original 'latest.hex' does not have the issue, so something may have changed since you last compiled it... just a heads up..

**Comment by glynhudson** [comment]
>Unrelated to this... I found a problem when I compile the firmware using all the right libraries as dictated by platform IO ... the call to rf12_initialise kills reception when it is made a 2nd time (Ie the lines
if ((now - last_rf_rest) > RF_RESET_PERIOD) {
rf12_initialize(nodeID, RF_freq, networkGroup); // Periodically reset RFM69CW to keep it alive :-(
}

Interesting, the version of JeeLib used to compile latest.hex is exactly the same as the version defined in `platfromio.ini`. Do you have a good method of testing this? How can try and replicate your reception dropping issue?

**Comment by alandpearson** [comment]
I can replicate this at will.  Let me know what you need me to do and i'd be happy to assist.
I can give you team viewer access if you need to my environment if that helps ?

Personally, I don't like resetting the thing every 60 seconds, as I have a busy little RF network ... 

I noticed the tmonTx code doesn't have this reset in it and I assume it uses the same RFM69cw.
Although that said, when I compiled the emonglcd code using the jcw jee lib it went almost deaf. Compiling it with the openergymonitor/jeelib restored it's hearing... 

Oh jee lib, how we love you !

**Comment by glynhudson** [comment]
>Personally, I don't like resetting the thing every 60 seconds, 

Yeah me too, I would be nice not to do this. I'll compile a test with the rest code removed and see how reliable it is. So you have been running the emonPi without this period reset and it's been reliable receving RF? For how long have you tested? 

I've just pushed a test to `remove-rest-hack` branch: https://github.com/openenergymonitor/emonpi/tree/remove-reset-hack

**Pull request merged**
