### PR TITLE
Refactor emonPiLCD

### PR DESCRIPTION
**Pull request by bwduncan**
Hi guys,

I've had my emonPi since the start of the year and I'm very happy. I wanted to give something back and I thought a good place to start would be to use some of my python experience to tidy up the code a bit. These are pretty big changes and I've been following your commits but as it's getting harder to keep up I feel it's time to offer them for your judgement!

Apologies if I'm stepping on anyone's toes here. If you like what you see I'm happy to port your most recent changes to this style.

Thanks,
Bruce

### CODE REVIEW

**Comment by glynhudson** [comment]
Wow, thanks a lot. As you can probably tell I'm not a very experienced pythonist. The code was certainly functional rather than exemplary. I was finding maintainability was starting to become as issue as I was started to add new features recently e.g. Display 3G connection status and signal level from a GSM dongle

I'm currently working through your changes. I am getting some errors when I try and run. Do I need to pip install some new modules? I notice you have added some modules to the import list. 

```
 File "./emonPiLCD.py", line 123, in backlight
    self.backlight = state
  File "./emonPiLCD.py", line 122, in backlight
    self.logger.debug("LCD backlight: " + repr(state))
  File "/usr/lib/python2.7/logging/__init__.py", line 1147, in debug
    if self.isEnabledFor(DEBUG):
  File "/usr/lib/python2.7/logging/__init__.py", line 1359, in isEnabledFor
    return level >= self.getEffectiveLevel()
RuntimeError: maximum recursion depth exceeded

```

Once working I will commit to a dev branch and look at adding in my latest changes

**Comment by bwduncan** [comment]
Woops! Sorry about that. Try now.

I'm glad you like the look of these changes. There are no new dependencies and in fact I've removed the "uptime" module which is no longer needed.

I've attempted to merge in your latest changes. Let me know if it still does what you intended. There are a few ways we could look at to improve the long-term maintainability and testability of the code, but I'd like to get it working first!

Cheers,
Bruce

**Comment by glynhudson** [comment]
Excellent! Great, it's now working. Switching between pages using the push button is *much* snappier. I love it. Got an issue where the script returns 'Ethernet: YES' (but no IP address) when Wifi is connected but not Ethernet is not. It took a while to understand the part of the code which returns the IP address. It turns out an an eval() was needed to ensure the boolean if eth active etc was evaluated: https://github.com/openenergymonitor/emonpi/blob/development/lcd/emonPiLCD.py#L313

I have merged and pushed to the dev branch for some more testing. I will test with 3G dongle tomorrow.: https://github.com/openenergymonitor/emonpi/blob/development. 

Thanks so much for your help. Have you got an account on our shop? Would you like me to credit your account with some store credit in case you need and hardware bits n bobs in the future?

**Comment by glynhudson** [comment]
Would it be possible to log to the logfile the lcd[0] and lcd[1] text each time the button is pressed for debugging? It would be great to have some way to trigger the page change remotely for debugging.

**Comment by bwduncan** [comment]
Hi Glyn,

That's great that it's working for you. There's only limited testing I can do myself! That's interesting that you need eval(). eval is quite a big hammer for this nut so I'll have a look at reproducing this here. I think I probably just don't understand redis yet...

Yes, there is logging in there already, just change INFO to DEBUG on line 165. I think one of the things we need is a way to specify debug logging (command line option, config file?), so that we can have more debugging and only enable it when it's required.

Yes, I did this too! You can in fact toggle the button in a slightly hacky way, just "echo -n 1  | sudo tee /proc/$(cat /var/run/emonPiLCD.pid)/fd/7" and it should switch.

Of course if you think redis or mqtt are a better fit for these tasks I'd be interested to learn.

I do have an account on your shop and I would be honoured to be helped along in my quest to monitor everything my house does! My email address is my github username at gmail.com.

Thanks!
Bruce

**Comment by glynhudson** [comment]
Hi Bruce,

I was aware of the debug log option, however when turned on it logs the LCD
strings ever few seconds which swamps the log file. What I'm after is just
to print the current LCD strings to log file on button press. This won't
hammer the log too much and can be logged under INFO.

Nice, idea. I've just tested $echo -n 1 | sudo tee /proc/$(cat
/var/run/emonPiLCD.pid)/fd/7 and it does not seem to work for me. Nothing
happens. I'm testing this on a RasPi3 if that makes a difference! If this
method worked it should be a sufficient hack for testing. It can be added
as a comment on the top of the script or made into a bash script to be
easily executed.

Feel free to edit the daemon script if you want to add loglevel config
options at runtime.

On a separate topic (rather awkwardly) the Rasi3 displayed it's on-board
Wifi signal strength in a different way which results in a -% being
displayed on the LCD:

Rasi2 with Edimax Dongle:

```
pi@emonpi:~ $ iwconfig wlan0
wlan0     IEEE 802.11bgn  ESSID:"OpenEnergyMonitor"  Nickname:"<WIFI@REALTEK
>"
          Mode:Managed  Frequency:2.422 GHz  Access Point:
00:1D:AA:34:1D:98
          Bit Rate:150 Mb/s   Sensitivity:0/0
          Retry:off   RTS thr:off   Fragment thr:off
          Power Management:off
          Link Quality=100/100  Signal level=99/100  Noise level=0/100
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0
```

RasPi3 with onboard wifi:

```
pi@emonpi:~ $ iwconfig wlan0
wlan0     IEEE 802.11bgn  ESSID:"OpenEnergyMonitor"
          Mode:Managed  Frequency:2.422 GHz  Access Point:
00:1D:AA:34:1D:98
          Bit Rate=43 Mb/s   Tx-Power=1496 dBm
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Power Management:on
          Link Quality=59/70  Signal level=-51 dBm
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0
```

As you can see on the Pi2 `Signal level=99/100` we use the 99 and display
it as a % on the emonPi LCD. On the RasPi3 it's not so easy. I propose we
use `Link Quality=59/70` and convert this into percentage and then display
in the usual way. The way to detect this could be to initially return
Signal Level and if this is XX/100 then simple return XX as %, if not (as
in case of RasPi3) we then look at Link Quality and convert to %. The first
solution I thought of was to just use Link Quality for both devices,
however the Link Quality for the Pi2 with Edimax is always 100/100 even
when signal strength drops to 50% so is incorrect.

 I wonder if there could be more variations for different Wifi hardware?
You don't happen to have the official RasPi USB Wifi dongle to hand do you:
https://www.raspberrypi.org/products/usb-wifi-dongle/

I have added £40 to your shop credit :-)

On 3 March 2016 at 12:18, bwduncan <notifications@github.com> wrote:

> Hi Glyn,
>
> That's great that it's working for you. There's only limited testing I can
> do myself! That's interesting that you need eval(). eval is quite a big
> hammer for this nut so I'll have a look at reproducing this here. I think I
> probably just don't understand redis yet...
>
> Yes, there is logging in there already, just change INFO to DEBUG on line
> 165. I think one of the things we need is a way to specify debug logging
> (command line option, config file?), so that we can have more debugging and
> only enable it when it's required.
>
> Yes, I did this too! You can in fact toggle the button in a slightly hacky
> way, just "echo -n 1 | sudo tee /proc/$(cat /var/run/emonPiLCD.pid)/fd/7"
> and it should switch.
>
> Of course if you think redis or mqtt are a better fit for these tasks I'd
> be interested to learn.
>
> I do have an account on your shop and I would be honoured to be helped
> along in my quest to monitor everything my house does! My email address is
> my github username at gmail.com.
>
> Thanks!
> Bruce
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openenergymonitor/emonpi/pull/9#issuecomment-191729912>
> .
>



-- 
Glyn Hudson

http://megni.co.uk
http://adventuresplusnorthwales.blogspot.com

**Comment by glynhudson** [comment]
I'm not sure what's happened but since merged this into master the backlight timeout does not seem to be working. Backlight is always on. Just checking if you are also experiencing this issue after switching to Master branch? If so, I'll look into it...

**Comment by bwduncan** [comment]
Hi Glyn

Yes this is because the lcd driver turns the backlight on every time it
does a write. I have plans to fix this! I've got the day off tomorrow so
I'll try to get you a pull request asap

Bruce

**Comment by glynhudson** [comment]
Hi Bruce,

Did you manage to make any progress on this? Would it be possible to halt LCD updating during periods when the BL is off? Let me know if you would like me to try and investigate. I have had head from users reporting that their hall ways is kept alight due to the emonPi LCD BL staying on all the time! Afraid I did not notice this until I merged into Master.

**Comment by bwduncan** [comment]
Hi Glyn,

Oh no, I'm really sorry to hear that! I have made a patch but unfortunately it doesn't work... I've been really busy this weekend but I should be able to do some testing tonight and hopefully get you a working patch.

It might be helpful to see the datasheet for the LCD controller if you have it to hand?

Bruce

**Comment by glynhudson** [comment]
No worries, see attached. 
[PCF8574.pdf](https://github.com/openenergymonitor/emonpi/files/163574/PCF8574.pdf)

**Comment by bwduncan** [comment]
Success! Nice simple patch. Sorry for the inconvenience. Do you want a new pull request or are you happy just to pull from my master branch?

I'll get to work on a config file to aid debugging and the eval problem.

Also, for me the button sometimes just doesn't work. Have you noticed this? I see that the debounce time is set to 1s. This seems like a long time. I'll play with this sometime this week.

Cheers,
Bruce

**Comment by glynhudson** [comment]
Excellent! Thanks you so much. A PR is best. Yes the buttons are not
amazing quality I would really like to source a replacement. Tweaking
denounce might help. I have noticed sometimes the LCD advances a page on
it's own accord.

On 8 March 2016 at 22:58, bwduncan <notifications@github.com> wrote:

> Success! Nice simple patch. Sorry for the inconvenience. Do you want a new
> pull request or are you happy just to pull from my master branch?
>
> I'll get to work on a config file to aid debugging and the eval problem.
>
> Also, for me the button sometimes just doesn't work. Have you noticed
> this? I see that the debounce time is set to 1s. This seems like a long
> time. I'll play with this sometime this week.
>
> Cheers,
> Bruce
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openenergymonitor/emonpi/pull/9#issuecomment-194006648>
> .
>



-- 
Glyn Hudson

http://megni.co.uk
http://adventuresplusnorthwales.blogspot.com

**Pull request merged**
